In [1]:
import numpy as np 

In [2]:
# Defining all the matrices and vectors 

matrix_A1 = np.array([[2.34332898, -0.11253278, -0.01485349, 0.33316649, 0.71319625],
            [-0.11253278, 1.67773628, -0.32678856, -0.31118836, -0.43342631],
            [-0.01485349, -0.32678856, 2.66011353, 0.85462464, 0.16698798],
            [0.33316649, -0.31118836, 0.85462464, 1.54788582, 0.32269197],
            [0.71319625, -0.43342631, 0.16698798, 0.32269197, 3.27093538]])

matrix_A2 = np.array([[2.34065520, -0.05353743, 0.00237792, 0.32944082, 0.72776588],
            [-0.05353743, 0.37604149, -0.70698859, -0.22898376, -0.75489595],
            [0.00237792, -0.70698859, 2.54906441, 0.87863502, 0.07309288],
            [0.32944082, -0.22898376, 0.87863502, 1.54269444, 0.34299341],
            [0.72776588, -0.75489595, 0.07309288, 0.34299341, 3.19154447]])

vector_b1 = np.transpose(np.array([[3.55652063354463, -1.86337418741501, 5.84125684808554, -1.74587299057388, 0.84299677124244]]))

vector_b2 = np.transpose(np.array([[3.55653063354463, -1.86337418741501, 5.84125684808554, -1.74587299057388, 0.84299677124244]]))



In [3]:
# Solving the equations
vector_y1 = np.linalg.solve(matrix_A1, vector_b1)
vector_y1_prim = np.linalg.solve(matrix_A1, vector_b2)
vector_y2 = np.linalg.solve(matrix_A2, vector_b1)
vector_y2_prim = np.linalg.solve(matrix_A2, vector_b2)

In [4]:
# A1y1 = b result
vector_y1

array([[ 2.03163246],
       [-1.03652186],
       [ 3.22032664],
       [-3.52251753],
       [-0.1394951 ]])

In [5]:
# A1y'1 = b' result
vector_y1_prim

array([[ 2.03163717],
       [-1.0365219 ],
       [ 3.22032706],
       [-3.52251858],
       [-0.13949605]])

In [6]:
# A2y2 = b result
vector_y2

array([[ 1.99998045],
       [-0.33814056],
       [ 3.42431038],
       [-3.56662167],
       [ 0.0329788 ]])

In [7]:
# A2y'2 = b' result
vector_y2_prim

array([[  3.42873475],
       [-31.86258865],
       [ -5.78337449],
       [ -1.57579144],
       [ -7.75237481]])

In [8]:
# Calculating Euclidean norms 
norm_1 = np.linalg.norm(vector_y1 - vector_y1_prim)
norm_2 = np.linalg.norm(vector_y2 - vector_y2_prim)


In [9]:
# Delta 1 
norm_1

4.934587135529891e-06

In [10]:
# Delta 2 
norm_2

33.84063773776324

In [11]:
np.linalg.cond(matrix_A1)

4.00000002506492

In [12]:
np.linalg.cond(matrix_A2)

320612863.37996066