In [91]:
import numpy as np 
np.set_printoptions(precision=5, suppress = True)

matrix_M = np.array([[3, 6, 6, 9], 
                 [1, 4, 0, 9],
                 [0, 0.2, 6, 12],
                 [0, 0, 0.1, 6]])

matrix_B = np.array([[3, 4, 2, 4], 
                 [4, 7, 1, -3],
                 [2, 1, 3, 2],
                 [4, -3, 2, 2]])

In [92]:
def iteration_qr(matrix):
    matrix_Q, matrix_R = np.linalg.qr(matrix)
    return np.matmul(matrix_R, matrix_Q)

def qr_check_stop(matrix, stop_value=10**-15)->bool:
    values = []
    for i in range(1, len(matrix)):
        values.append(abs(matrix[i][i-1]))
    if all(i < stop_value for i in values):
        return True
    return False

def get_diagonal_elements(matrix):
    return [matrix[x][x] for x, _ in enumerate(matrix)]

def iteration_power(matrix, vector):
    y_hat = np.matmul(matrix, vector)
    return y_hat / np.linalg.norm(y_hat)

def power_check_stop(a_vec, b_vec, stop_diff=10**-15)->bool:
    return np.linalg.norm(a_vec - b_vec) < stop_diff

def power_get_eigenvalue(matrix, vector):
    return np.matmul(matrix, vector)[0] / y_new[0]
          

In [93]:
# Algorytm QR
result =  iteration_qr(matrix_M)

while not qr_check_stop(result):
    result = iteration_qr(result)
    
get_diagonal_elements(result)

[7.230992309419286, 5.900157268333133, 4.8158065906820475, 1.0530438315655382]

In [94]:
np.linalg.eig(matrix_M)[0]
# Wyniki się zgadzają

array([1.05304, 4.81581, 5.90016, 7.23099])

In [95]:
# Metoda potęgowa
y_new = np.array([5 for _ in enumerate(matrix_B)])
y_hat = iteration_power(matrix_B, y_new)

while not power_check_stop(y_hat, y_new):
    y_new = y_hat
    y_hat = iteration_power(matrix_B, y_new)

y_new
power_get_eigenvalue(matrix_B, y_new)

10.015982848255211

In [96]:
max(np.linalg.eig(matrix_B)[0])
# Wyniki się zgadzają

10.015982848255218

In [97]:
y_new

array([0.5583 , 0.77621, 0.28679, 0.05965])

In [98]:
np.linalg.eig(matrix_B)[1]

array([[-0.61383,  0.40642,  0.5583 ,  0.38254],
       [ 0.41866,  0.00966,  0.77621, -0.47131],
       [-0.07645, -0.87323,  0.28679,  0.3865 ],
       [ 0.66489,  0.26872,  0.05965,  0.69437]])